### ISSUE TITLE
Pi-specific vs. Workstation-specific setup

### ISSUE THREAD

**Issue by rjehangir** [bluerobotics/BlueROV#1]
The setup instructions currently apply to both the Pi and Workstation but there are several specifics that can be split. The dependencies for camera are not needed on workstation and the raspicam_node is not needed (and won't compile) on the workstation.

**Comment by joshvillbrandt** [comment]
Good catch!

There are currently setup instructions that apply to the Pi, setup instructions that apply to the workstation, and setup instructions that apply to both. So it's not that the separate Pi instructions don't exist, I just need to move the camera stuff out of the shared instructions.

You mentioned "several" specifics that can be split - did you notice anything else that is in the wrong location?

**Comment by rjehangir** [comment]
Here's what I noticed that should be split off from the combined instructions
- Pi-specific dependencies from apt-get
- Cloning the Raspicam_node

**Comment by joshvillbrandt** [comment]
Which Pi-specific apt dependencies are listed in the combined instructions? I wasn't able to identify any.

A note has been added to only install `raspicam_node` for the Pi.

**Comment by rjehangir** [comment]
You are right. There are no Pi-specific apt dependencies listed.

**Comment by joshvillbrandt** [comment]
:+1:
