### ISSUE TITLE
Kinetic build instructions missing

### ISSUE THREAD

**Issue by martijnbastiaan** [bluerobotics/BlueROV#13]
Hi!

There are currently no build instructions for Kinetic. It is slightly more involved than just replacing indigo with kinetic, unfortunately, due to a non-specified dependency.

See pull request https://github.com/bluerobotics/bluerov-ros-pkg/pull/12.

**Comment by jaxxzer** [comment]
Marking as `wontfix`, this repository is retired and unsupported.
