### ISSUE TITLE
Dynamic Positioning

### ISSUE THREAD

**Issue by neweirik** [bluerobotics/BlueROV#14]
Hi, Im going to write a dynamic positioning system foryour ROV. I tough that you had done so already, however there is nothing like that in this repo. I have the bluerov and the pixhawk, I also have a rostopic with "real position" relative to the "world" frame. Do you have a way for me to send in reference position and real position in xyz? Or do I need to write my own controller? Im going to use the tegra tx1 for video streaming. Im going to work on this for the next weeks and really hope to get a really stable ROV at the end!

-Eirik

**Comment by binary42** [comment]
Hi Eirik, what exactly do you mean by dynamic positioning system? My suggestion for you is to bring this up on BlueRobotics forum and have a chat with the folks on it first. This is an incredible hard problem, even when on the surface, much more so below with the given capabilities of the ROV, weight, power, etc. There are many people here that are familiar with dynamics and controls, and would have good input before you embark on something that is perhaps more difficult than you think. How are you getting real position? what filtering methods are you using to fuse your update and correction sensors? and so forth. Post on the forum and we can have a good conversation.

Regards, Jim

**Comment by neweirik** [comment]
What Im using for position is a company secret, Im using ekf for filtering, however I dont see the problem of positioning the ROV relative to a given point when accurate odometry is provided. With your thrusters is would not take to long slapping on some pid regulators and tuning them my selves. I will post on the forum and take it from there.

**Comment by binary42** [comment]
ah ....(really long message deleted)... ok. Best of luck to you.

**Comment by binary42** [comment]
BlueROV Please close this thread. Unrelated to development issue.
