### ISSUE TITLE
Lights on the BlueROV2

### ISSUE THREAD

**Issue by sl13** [bluerobotics/BlueROV#15]
Hi!

How can I turn on the lights on the BlueROV2 with your package via /mavros/rc/override?
I was looking in your teleop_joy.cpp code but I think there is no free channel for the light control (channel 7 on the pixhawk). Is this right or is there somewhere a opportunity to control the light channel?

**Comment by joshvillbrandt** [comment]
CC @rjehangir

**Comment by jaxxzer** [comment]
Marking as `wontfix`, this repository is retired and unsupported.
