### ISSUE TITLE
Missing urdf for BlueROV2

### ISSUE THREAD

**Issue by clydemcqueen** [bluerobotics/BlueROV#16]
There's no urdf for the BlueROV2.

I'm working on a BlueROV2 urdf file, and would be happy to submit a PR if there's interest.

**Comment by chapulino** [comment]
oh Thank you
 Asi podre pobarlo


2017-09-20 18:43 GMT+02:00 Clyde McQueen <notifications@github.com>:

**Comment by jaxxzer** [comment]
Marking as `wontfix`, this repository is retired and unsupported.
