### ISSUE TITLE
mavlink vs mavros

### ISSUE THREAD

**Issue by rjehangir** [bluerobotics/BlueROV#3]
The usage instructions specify a package called "mavlink" but it should be "mavros".

**Comment by joshvillbrandt** [comment]
The instructions in `setup.md` currently call for `ros-indigo-mavros` and `ros-indigo-mavros-extras` to be installed (which also installs the `mavlink` package.) Did this not work for you?

**Comment by rjehangir** [comment]
These don't work:
rosrun mavros mavlink
rosrun mavlink mavlink

This does work:
rosrun mavros mavros

I see that there is a mavlink package so I might just be confused on operation here.

**Comment by joshvillbrandt** [comment]
Oh, you did say usage instructions. My bad.

You actually shouldn't be launching `mavlink` or `mavros` direction, but should instead be using the supplied `apm.launch` file. An upcoming commit includes these directions.
