### ISSUE TITLE
Pi setup vcos header files missing

### ISSUE THREAD

**Issue by rjehangir** [bluerobotics/BlueROV#4]
I get the following error message when following the setup instructions and compiling the code on the RPi:

``` bash
[ 75%] In file included from /usr/include/interface/vcos/vcos_assert.h:149:0,
                 from /usr/include/interface/vcos/vcos.h:114,
                 from /home/ubuntu/catkin_ws/src/raspicam_node/src/RaspiCLI.cpp:46:
/usr/include/interface/vcos/vcos_types.h:38:33: fatal error: vcos_platform_types.h: No such file or directory
 #include "vcos_platform_types.h"
                                 ^
compilation terminated.
In file included from /usr/include/interface/vcos/vcos_assert.h:149:0,
                 from /usr/include/interface/vcos/vcos.h:114,
                 from /home/ubuntu/catkin_ws/src/raspicam_node/src/RaspiCamControl.cpp:32:
/usr/include/interface/vcos/vcos_types.h:38:33: fatal error: vcos_platform_types.h: No such file or directory
 #include "vcos_platform_types.h"
                                 ^
compilation terminated.
```

**Comment by joshvillbrandt** [comment]
I originally got that too. Some Google searching led me to `sudo ln -s /usr /opt/vc`. Did you do that as suggested in [Setup.md / Setup OS Essentials](https://github.com/bluerobotics/bluerov-ros-pkg/blob/master/docs/Setup.md#setup-os-essentials)?

**Comment by rjehangir** [comment]
I thought I did, but according to bash history I didn't... It works now! Thank you.

**Comment by joshvillbrandt** [comment]
:+1:

**Comment by joshvillbrandt** [comment]
Maybe you ran a bunch of bunch commands all at once...? Normally, bash will continue on to subsequent commands even if previous ones fail. Try `set -e` at the top of a bash script (or during a session?) to make bash halt on the first error.
