### ISSUE TITLE
dynamic_reconfigure issue

### ISSUE THREAD

**Issue by binary42** [bluerobotics/BlueROV#8]
Please check my work but it looks like the run_depend and build_depend for dynamic reconfigure is missing for the bluerov_apps package. Upon compilation, 

CMake Error at CMakeLists.txt:23 (generate_dynamic_reconfigure_options):
  Unknown CMake command "generate_dynamic_reconfigure_options".

is thrown. Adding dynamic reconfigure to the cmake find_package and the run and build depends in the package.xml resolves this issue.

If this sounds resonable I'll get a merge request in for the fix. Please confirm. (also, Josh, do you want the PCL depends to go away?)

**Comment by jaxxzer** [comment]
Marking as `wontfix`, this repository is retired and unsupported.
