### ISSUE TITLE
Typos in setup of udev rules

### ISSUE THREAD

**Issue by binary42** [bluerobotics/BlueROV#9]
In the instructions we have:
# udev rules

sudo cp ~/catkin_ws/src/bluerov/debian/99-bluerov.rules /etc/udev/rules.d/
sudo cp ~/catkin_ws/src/bluerov_apps/debian/99-bluerov-apps.rules /etc/udev/rules.d/

these fail do to the previous symbolic link creation. The correct instructions should be:
# udev rules

sudo cp ~/repos/bluerov-ros-pkg/bluerov/debian/99-bluerov.rules /etc/udev/rules.d/
sudo cp ~/repos/bluerov-ros-pkg//bluerov_apps/debian/99-bluerov-apps.rules /etc/udev/rules.d/

**Comment by jaxxzer** [comment]
Marking as `wontfix`, this repository is retired and unsupported.
